// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactChess.Server.Models;

public partial class Account
{
    public int Id { get; set; }

    public string Login { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool IsAdmin { get; set; }

    //public virtual ICollection<Ban> Bans { get; set; } = new List<Ban>();

    public virtual Player? Player { get; set; }
}