// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactChess.Server.Models;

public partial class Ban
{
    public int Id { get; set; }

    public int AccusedId { get; set; }

    public int AdminId { get; set; }

    public string Reason { get; set; }
    public DateTime Start {  get; set; }
    public TimeSpan Term { get; set; }

    public virtual Account Admin { get; set; }

    public virtual Account Accused { get; set; }
}