// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ReactChess.Server.Models;

public partial class ChessContext : DbContext
{
    public ChessContext(DbContextOptions<ChessContext> options)
        : base(options)
    {
        Database.EnsureCreated();
    }

    public virtual DbSet<Account> accounts { get; set; }

    public virtual DbSet<Ban> bans { get; set; }

    public virtual DbSet<Elo> elos { get; set; }

    public virtual DbSet<Game> games { get; set; }

    public virtual DbSet<Player> players { get; set; }

    public virtual DbSet<TimeFormat> timeFormats { get; set; }

    public virtual DbSet<Tournament> tournaments { get; set; }
    public virtual DbSet<Move> moves { get; set; }
    public virtual DbSet<Friendship> friendships { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("Host=localhost; Port=5432;Database=Chess;Username=postgres;Password=12345678");
    }
}