// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactChess.Server.Models;

public partial class Elo
{
    public int Id { get; set; }

    public int Number { get; set; }

    public int PlayerId { get; set; }

    public int FormatId { get; set; }

    public virtual TimeFormat Format { get; set; }

    public virtual Player Player { get; set; }
}