// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactChess.Server.Models;

public partial class Game
{
    public int Id { get; set; }
    public string Status { get; set; }
    public int WhitesId { get; set; }
    public int BlacksId { get; set; }
    public int FormatId { get; set; }
    public int? TournamentId { get; set; }
    public DateTime StartTime { get; set; }
    public virtual Player Blacks { get; set; }
    public virtual Player Whites { get; set; }
    public virtual TimeFormat Format { get; set; }
    public virtual Tournament? Tournament { get; set; }
}