// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactChess.Server.Models;

public partial class Player
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int AccountId { get; set; }

    public virtual Account Account { get; set; }

}