// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactChess.Server.Models;

public partial class TimeFormat
{
    public int Id { get; set; }

    public string Name { get; set; }

    public TimeSpan Time { get; set; }
    public TimeSpan AddTime { get; set; }
}