// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReactChess.Server.Models;

public partial class Tournament
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int PassElo { get; set; }

    public string PassTitle { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public virtual ICollection<Game> Games { get; set; } = new List<Game>();
}